# Generated by Django 5.0.3 on 2024-04-02 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktkosh', '0002_bloodrequest_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raktkosh.userprofile'),
        ),
    ]
