# Generated by Django 5.0.3 on 2024-04-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raktkosh', '0004_blooddonate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonate',
            old_name='donor',
            new_name='user',
        ),
    ]
